// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxs3bgND8oH8U132qWyzOiVMzLrHzdFTc',
    appId: '1:262400982478:web:b916598c4936f17e8e3f9f',
    messagingSenderId: '262400982478',
    projectId: 'simple-chat-6eee6',
    authDomain: 'simple-chat-6eee6.firebaseapp.com',
    storageBucket: 'simple-chat-6eee6.appspot.com',
    measurementId: 'G-6GM0Z186YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBCdG5eG5WUqcYazUeH-6q5Zr7KxPIvI',
    appId: '1:262400982478:android:a78a34443b1a14da8e3f9f',
    messagingSenderId: '262400982478',
    projectId: 'simple-chat-6eee6',
    storageBucket: 'simple-chat-6eee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5p8cargcMvC5CZ3iweWht2wj3_p_gOHE',
    appId: '1:262400982478:ios:fddf61c8b744af508e3f9f',
    messagingSenderId: '262400982478',
    projectId: 'simple-chat-6eee6',
    storageBucket: 'simple-chat-6eee6.appspot.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5p8cargcMvC5CZ3iweWht2wj3_p_gOHE',
    appId: '1:262400982478:ios:fddf61c8b744af508e3f9f',
    messagingSenderId: '262400982478',
    projectId: 'simple-chat-6eee6',
    storageBucket: 'simple-chat-6eee6.appspot.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxs3bgND8oH8U132qWyzOiVMzLrHzdFTc',
    appId: '1:262400982478:web:f147021d12ba9ae88e3f9f',
    messagingSenderId: '262400982478',
    projectId: 'simple-chat-6eee6',
    authDomain: 'simple-chat-6eee6.firebaseapp.com',
    storageBucket: 'simple-chat-6eee6.appspot.com',
    measurementId: 'G-BBNQ0K7Y58',
  );
}
